/** Scottish football teams with verified ESPN IDs. */
export const SCOTTISH_TEAMS = [
    // Premiership (sco.1)
    { espnId: 263, name: 'Aberdeen', shortName: 'ABE' },
    { espnId: 256, name: 'Celtic', shortName: 'CEL' },
    { espnId: 261, name: 'Dundee', shortName: 'DUN' },
    { espnId: 264, name: 'Dundee United', shortName: 'DUU' },
    { espnId: 254, name: 'Falkirk', shortName: 'FALK' },
    { espnId: 262, name: 'Heart of Midlothian', shortName: 'HOM' },
    { espnId: 258, name: 'Hibernian', shortName: 'HIBS' },
    { espnId: 260, name: 'Kilmarnock', shortName: 'KIL' },
    { espnId: 259, name: 'Livingston', shortName: 'LIV' },
    { espnId: 266, name: 'Motherwell', shortName: 'MOT' },
    { espnId: 257, name: 'Rangers', shortName: 'RAN' },
    { espnId: 250, name: 'St Mirren', shortName: 'STM' },
    // Championship (sco.2)
    { espnId: 2500, name: 'Airdrieonians', shortName: 'AIR' },
    { espnId: 252, name: 'Arbroath', shortName: 'ARB' },
    { espnId: 248, name: 'Ayr United', shortName: 'AYR' },
    { espnId: 265, name: 'Dunfermline Athletic', shortName: 'DFA' },
    { espnId: 411, name: 'Greenock Morton', shortName: 'MORT' },
    { espnId: 247, name: 'Partick Thistle', shortName: 'PAR' },
    { espnId: 422, name: "Queen's Park", shortName: 'QUE' },
    { espnId: 249, name: 'Raith Rovers', shortName: 'RRFC' },
    { espnId: 251, name: 'Ross County', shortName: 'ROSS' },
    { espnId: 267, name: 'St Johnstone', shortName: 'STJ' },
    // League One (sco.3)
    { espnId: 403, name: 'Alloa Athletic', shortName: 'ALL' },
    { espnId: 2613, name: 'Cove Rangers', shortName: 'COVE' },
    { espnId: 421, name: 'East Fife', shortName: 'EFIF' },
    { espnId: 409, name: 'Hamilton Academical', shortName: 'HAM' },
    { espnId: 253, name: 'Inverness Caledonian Thistle', shortName: 'ICT' },
    { espnId: 18018, name: 'Kelty Hearts', shortName: 'KEL' },
    { espnId: 414, name: 'Montrose', shortName: 'MON' },
    { espnId: 416, name: 'Peterhead', shortName: 'PET' },
    { espnId: 406, name: 'Queen of the South', shortName: 'QOS' },
    { espnId: 405, name: 'Stenhousemuir', shortName: 'STE' },
    // League Two (sco.4)
    { espnId: 7166, name: 'Annan Athletic', shortName: 'ANN' },
    { espnId: 255, name: 'Clyde', shortName: 'CLY' },
    { espnId: 415, name: 'Dumbarton', shortName: 'DUM' },
    { espnId: 17582, name: 'East Kilbride', shortName: 'EKB' },
    { espnId: 2832, name: 'Edinburgh City', shortName: 'EDI' },
    { espnId: 419, name: 'Elgin City', shortName: 'ELG' },
    { espnId: 408, name: 'Forfar Athletic', shortName: 'FOR' },
    { espnId: 18015, name: 'Spartans FC', shortName: 'SFC' },
    { espnId: 417, name: 'Stirling Albion', shortName: 'STI' },
    { espnId: 407, name: 'Stranraer', shortName: 'STR' },
];
